site_name: My Super Cool Respository


# Repository
repo_name: My Super Cool Respository
repo_url: https://github.com/allfed/My Super-Cool-Respository
edit_uri: ""
# Copyright
copyright: Me

docs_dir: "docs/sources"

plugins:
  - search

theme:
  name: 'readthedocs'
  custom_dir: 'docs'
  palette:
    primary: 'white'
  logo: 'assets/images/logo_full.svg'
  favicon: 'assets/images/favicon.svg'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - instant
nav:

